// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW8haRdNkV5nDNIqWF9pH-GZkiCM__bFc',
    appId: '1:403265499826:web:fa5ed455ca4f32c317cfab',
    messagingSenderId: '403265499826',
    projectId: 'amazn-caa2b',
    authDomain: 'amazn-caa2b.firebaseapp.com',
    storageBucket: 'amazn-caa2b.appspot.com',
    measurementId: 'G-5E65E55D59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA_cLl2jR4zISJIAWmgsh1nX9Dfl4CwnA',
    appId: '1:403265499826:android:9fbb97daf0342e2217cfab',
    messagingSenderId: '403265499826',
    projectId: 'amazn-caa2b',
    storageBucket: 'amazn-caa2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZjiTm9hz_06CAsB2w6sojBtfc9OeqSuQ',
    appId: '1:403265499826:ios:dae7cfa525c6721c17cfab',
    messagingSenderId: '403265499826',
    projectId: 'amazn-caa2b',
    storageBucket: 'amazn-caa2b.appspot.com',
    iosBundleId: 'com.example.amazonClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZjiTm9hz_06CAsB2w6sojBtfc9OeqSuQ',
    appId: '1:403265499826:ios:dae7cfa525c6721c17cfab',
    messagingSenderId: '403265499826',
    projectId: 'amazn-caa2b',
    storageBucket: 'amazn-caa2b.appspot.com',
    iosBundleId: 'com.example.amazonClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW8haRdNkV5nDNIqWF9pH-GZkiCM__bFc',
    appId: '1:403265499826:web:98037f6bc71dfd7f17cfab',
    messagingSenderId: '403265499826',
    projectId: 'amazn-caa2b',
    authDomain: 'amazn-caa2b.firebaseapp.com',
    storageBucket: 'amazn-caa2b.appspot.com',
    measurementId: 'G-1TK8JV8LK5',
  );
}
